modLoader = "javafml"
loaderVersion = "[33,)"
issueTrackerURL = "https://github.com/maxanier/Guide-API/issues"
license = "MIT"

[[mods]]
    modId="guideapi-vp"
    namespace="guideapi-vp"
    version="${version}"
    displayName="Guide-API VP"
    authors="Tombenpotter, TehNut, Maxanier"
    credits=""
    description="Simple mod guide creation"
    updateJSONURL="https://maxanier.de/projects/guideapi/versions.json"
    displayURL="https://maxanier.de/projects/guideapi"
    logoFile="logo.png"
    [[dependencies.guideeapi]]
        modId="forge"
        mandatory=true
        versionRange="[${forge_version},)"
        ordering="NONE"
        side="BOTH"
