modLoader="javafml"
loaderVersion="[27,)"
issueTrackerURL="https://github.com/maxanier/Guide-API/issues"

[[mods]]
    modId="guideapi-vp"
    namespace="guideapi-vp"
    version="${version}"
    displayName="Guide-API VP"
    authors="Tombenpotter, TehNut, Maxanier"
    credits=""
    description="Simple mod guide creation"
    [[dependencies.guideeapi]]
        modId="forge"
        mandatory=true
        versionRange="[${forge_version},)"
        ordering="NONE"
        side="BOTH"
